email_sender:
    smtp_server: 'smtp.sendgrid.net'
    smtp_port: 465
    sender: '------@gmail.com'
    user: 'apikey'
    password: ''
    queue_time: 5
    max_retry: 7
    send_opt: 1
slack:
    webhook_url: 'hooks.slack.com'
    webhook_path: '/services/_______________________'
    channel: '#test_bed'
    username: 'sb-bot'
    icon: ':satellite:'
ts_signal:
    future_regex: '[A-Z]{2,3}(F|G|H|J|K|M|N|Q|U|V|X|Z)\d{2}'