email_sender:
    smtp_server: 'mail.twc.com'
    smtp_port: 587
    sender: '____@roadrunner.com'
    queue_time: 5
    max_retry: 7
    send_opt: 1
slack:
    webhook_url: 'hooks.slack.com'
    webhook_path: '/services/_______________________'
    channel: '#test_bed'
    username: 'sb-bot'
    icon: ':satellite:'
